[metadata]
name = fred-forecaster
version = 0.1.1
description = Time series forecasting for FRED economic data
long_description = file: README.md
long_description_content_type = text/markdown
url = https://github.com/maxghenis/fred-forecaster
classifiers =
    Programming Language :: Python :: 3
    License :: OSI Approved :: MIT License
    Operating System :: OS Independent

[options]
packages = find:
python_requires = >=3.8
install_requires =
    numpy
    pandas
    fredapi
    scipy
    statsmodels
    matplotlib
    pymc
    arviz

[options.extras_require]
dev =
    pytest
    pytest-cov
    black
    isort
    flake8
    mypy
app =
    streamlit